name: npm test
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Istall Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository # as they are running in different vms, checkout and install is needed
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
#      - name: Install dependencies
#        run: npm ci               # or Install bats from first job
#      - run: npm run build --if-present
      - name: Install dependencies
        run: npm install
      - name: Run npm test
        run: npm test
