name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    permissions: 
      issues: write
    runs-on: ubuntu-latest
    env:
        NODE_VERSION: 14       
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        id: step1
        env:
          SHA: ${{ github.sha }}
        run: echo 'SHORT_SHA='${SHA::10} >> $GITHUB_OUTPUT
      - name: Create issue using REST API
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret2 }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{env.SUPER_SECRET}}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _ ${{steps.step1.outputs.SHORT_SHA}}_.\n\n ${{env.SUPER_SECRET}}"
            }' \
            --fail
          